### ISSUE TITLE
Add build instructions or actual binaries

### ISSUE THREAD

**Issue by danielleontiev** [vilikin/kafka-electron-client#2]
Build instructions and/or binaries are missing

**Comment by vilikin** [comment]
The app is still very much a work in progress, I will be writing a proper README & setting up Actions to release binaries automatically once this project is in a state where I'm happy to release it. :)

**Comment by vilikin** [comment]
Actually, if you'd like to try it out in this state already, I think it should be just one command to run the dev environment:

`yarn electron-dev` (that will spin up Overmind developer tools as well)

Requires at least Node and Java to be installed on your machine.

**Comment by danielleontiev** [comment]
I have successfully run application in dev environment, but when I try to package it I get:

```bash
$ /home/daniel/Desktop/kafka-electron-client/node_modules/.bin/electron-builder build
  • electron-builder  version=22.7.0 os=5.7.5-arch1-1
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • description is missed in the package.json  appPackageFile=/home/daniel/Desktop/kafka-electron-client/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=8.3.0 appOutDir=dist/linux-unpacked
  ⨯ Application entry file "build/electron.js" in the "/home/daniel/Desktop/kafka-electron-client/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                                               Error: Application entry file "build/electron.js" in the "/home/daniel/Desktop/kafka-electron-client/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                                   at error (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                                   at checkFileInArchive (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
                                                                                                                                                                                                   at LinuxPackager.checkFileInPackage (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:405:7)
                                                                                                                                                                                                   at LinuxPackager.sanityCheckPackage (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:456:5)
                                                                                                                                                                                                   at LinuxPackager.doPack (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:243:5)
                                                                                                                                                                                                   at LinuxPackager.pack (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
                                                                                                                                                                                                   at Packager.doBuild (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:444:9)
                                                                                                                                                                                                   at executeFinally (/home/daniel/Desktop/kafka-electron-client/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                                   at Packager._build (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:373:31)
                                                                                                                                                                                                   at Packager.build (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:337:12)
                                                                                                                                                                                                   at executeFinally (/home/daniel/Desktop/kafka-electron-client/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danielleontiev** [comment]
BTW, when I run `yarn electron-dev` it does not trigger backend compilation and I have to do it manually. Is this behavior correct?

**Comment by vilikin** [comment]
> BTW, when I run `yarn electron-dev` it does not trigger backend compilation and I have to do it manually. Is this behavior correct?

Ah, yea, forgot to include the step for building backend JAR. I think I should add it to the `electron-dev` command.

You can package the JAR by running `./gradlew shadowJar` in the backend directory.

> I have successfully run application in dev environment, but when I try to package it I get:
> 
> ```shell
> $ /home/daniel/Desktop/kafka-electron-client/node_modules/.bin/electron-builder build
>   • electron-builder  version=22.7.0 os=5.7.5-arch1-1
>   • loaded configuration  file=package.json ("build" field)
>   • loaded parent configuration  preset=react-cra
>   • description is missed in the package.json  appPackageFile=/home/daniel/Desktop/kafka-electron-client/package.json
>   • writing effective config  file=dist/builder-effective-config.yaml
>   • packaging       platform=linux arch=x64 electron=8.3.0 appOutDir=dist/linux-unpacked
>   ⨯ Application entry file "build/electron.js" in the "/home/daniel/Desktop/kafka-electron-client/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
>                                                                                                                                                                                                Error: Application entry file "build/electron.js" in the "/home/daniel/Desktop/kafka-electron-client/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
>                                                                                                                                                                                                    at error (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
>                                                                                                                                                                                                    at checkFileInArchive (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
>                                                                                                                                                                                                    at LinuxPackager.checkFileInPackage (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:405:7)
>                                                                                                                                                                                                    at LinuxPackager.sanityCheckPackage (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:456:5)
>                                                                                                                                                                                                    at LinuxPackager.doPack (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:243:5)
>                                                                                                                                                                                                    at LinuxPackager.pack (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
>                                                                                                                                                                                                    at Packager.doBuild (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:444:9)
>                                                                                                                                                                                                    at executeFinally (/home/daniel/Desktop/kafka-electron-client/node_modules/builder-util/src/promise.ts:12:14)
>                                                                                                                                                                                                    at Packager._build (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:373:31)
>                                                                                                                                                                                                    at Packager.build (/home/daniel/Desktop/kafka-electron-client/node_modules/app-builder-lib/src/packager.ts:337:12)
>                                                                                                                                                                                                    at executeFinally (/home/daniel/Desktop/kafka-electron-client/node_modules/builder-util/src/promise.ts:12:14)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Thanks for reporting, will check this out as some point. :)
